### ISSUE TITLE
Go on Go on!

### ISSUE THREAD

**Issue by chrisjohnson00** [timkippdev/ball-clock#2]
Learning Go!  Awesome man!

**Comment by timkippdev** [comment]
@chrisjohnson00 - yeah! been playing around with it for a couple years now. this project is based off a problem my cousin and I are doing and comparing our results to see who can get the fastest times. I have a lot more optimizations to make haha

**Comment by chrisjohnson00** [comment]
Nice!
Need a job? 😂 I'd love to work with you again!

**Comment by chrisjohnson00** [comment]
Recruiters gone wild

When they stalk you on you github projects
